__tests__/pages/index.spec.tsx

Fix the issue that I didn't format when I add prettier in #8

Format missed test file

---

.github/workflows/check.yml

Check building on CI

---

repositories/onAuthenticationStateChanged.ts

- Let it unsubscribe Firebase auth when it is unsubscribed.

Refactor onAuthenticationStateChanged()

---

components/PlayingCard.tsx
components/RankIcon.tsx
components/SuitIcon.tsx

Allow it for Storybook. I wish you don't use it in practical use.

Allow style prop

---

components/PlayingCard.stories.tsx
components/RankIcon.stories.tsx
components/SuitIcon.stories.tsx

- Reason
- Cannot use addon-knobs and addon-action in MDX
- Cannot get helped by TypeScript in MDX
- Comparing lines to write with output, CSF is better

Prefer Component Story Format

---

components/PlayingCardSelector.stories.tsx
components/PlayingCardSelector.tsx
components/SelectablePlayingCard.stories.tsx
components/SelectablePlayingCard.tsx

<SelectablePlayingCard> and <PlayingCardSelector>

---

components/SelectablePlayingCard.tsx
components/StreetActionSelector.stories.tsx
components/StreetActionSelector.test.tsx
components/StreetActionSelector.tsx
components/__snapshots__/StreetActionSelector.test.tsx.snap

<StreetActionSelector>

---

components/PopoverMenu/PopoverMenu.stories.tsx
components/PopoverMenu/PopoverMenu.tsx
components/PopoverMenu/PopoverMenuControlContext.ts
components/PopoverMenu/PopoverMenuItem.tsx
components/PopoverMenu/index.ts
package-lock.json
package.json

<PopoverMenu>

---

components/SelectablePlayingCard/SelectablePlayingCard.stories.tsx
components/SelectablePlayingCard/SelectablePlayingCard.tsx
components/SelectablePlayingCard/index.ts

Re-implement <SelectablePlayingCard> without antd

---

package-lock.json
package.json
pages/_app.tsx

Uninstall 📦antd

---

components/Button/Button.stories.tsx

Attack action() to <Button onClick={…}>

---

components/Button/Button.stories.tsx
components/Button/Button.tsx

Rename ButtonSize.regular to ButtonSize.medium

---

components/Card/Card.stories.tsx
components/Card/Card.tsx

Fix missing tweaks in #75

---

components/Icon/Icon.stories.tsx
components/Icon/Icon.tsx
components/Icon/index.ts

<ChevronDownIcon>, <ThumbsUpIcon>, <ThumbsDownIcon> and <Send>

---

components/TextArea/TextArea.stories.tsx
components/TextArea/TextArea.tsx
components/TextArea/index.ts

<Textarea>

---

components/Icon/Icon.tsx
components/SelectablePlayingCard/SelectablePlayingCard.tsx

Empty State of <SelectablePlayingCard>

---

components/Select/Option.tsx
components/Select/Select.stories.tsx
components/Select/Select.tsx
components/Select/index.ts

<Select> and <Option>

---

components/Button/Button.stories.tsx
components/Button/Button.tsx

- CSS for each variant and size to be applied by CSS Variables

Refactoring <Button>

---

components/TextArea/TextArea.stories.tsx
components/TextArea/TextArea.tsx

`disabled` option for <TextArea>

---

components/Button/Button.stories.tsx
components/Button/Button.tsx

`disabled` option for <Button>

---

components/Button/Button.stories.tsx
components/Icon/Icon.stories.tsx
components/Icon/Icon.tsx

<LoadingIcon>

---

components/StreetActionSelector/StreetActionSelector.test.tsx
components/StreetActionSelector/StreetActionSelector.tsx
components/StreetActionSelector/__snapshots__/StreetActionSelector.test.tsx.snap

Add tests for <StreetActionSelector>

---

components/StreetActionSelector/StreetActionSelector.stories.tsx
components/StreetActionSelector/StreetActionSelector.test.tsx
components/StreetActionSelector/StreetActionSelector.tsx
components/StreetActionSelector/__snapshots__/StreetActionSelector.test.tsx.snap

Delete minimum bet size restriction in <StreetActionSelector>

---

hooks/useRepository.tsx
pageComponents/PostDetailPage/PostDetailPage.tsx
pageComponents/PostDetailPage/index.ts
pages/_app.tsx
pages/posts/[postId].tsx
repositories/getPostById.ts

Here's example implementation for creating pages
Example URL: https://chipstackoverflow-git-post-page-scaffold.agnosticful.now.sh/posts/Z1BZtcL8lrIL13D2uTOp

Implement post detail page as a scaffold

---

components/PokerTable/Player.tsx
components/PokerTable/PokerTable.stories.tsx
components/PokerTable/PokerTable.tsx
components/PokerTable/PotIndicator.tsx
components/PokerTable/getPositionLabel.ts
components/PokerTable/index.ts

https://5ea496cde7f8090006cd5e1f--csof.netlify.app/?path=/docs/pokertable--example

<PokerTable>

---

models/PlayerHand.test.ts
models/PlayerHand.ts

Added `PlayerHand` model. It is a model represents a made hand (one pair, three of a kind, flush, etc.) and has its comparable strongness value.
We'll use this model to judge the winners for each game situation.

PlayerHand model

---

components/HandPlayer/HandPlayer.stories.tsx
components/HandPlayer/HandPlayer.tsx
components/HandPlayer/index.ts

<HandPlayer>

---

pageComponents/PostDetailPage/HandPlayerSection.tsx
pageComponents/PostDetailPage/PostAnswers.tsx
pageComponents/PostDetailPage/PostBody.tsx
pageComponents/PostDetailPage/PostDetailPage.tsx
pageComponents/PostDetailPage/PostTitle.tsx

Post View Page

---

.github/workflows/check.yml
package.json

Delete “dry-build” GitHub Action

---

repositories/createComment.ts

createComment() repository function

---

hooks/useCommentCreation.ts
pageComponents/PostDetailPage/AnswerListItem.tsx

Implement comment creation feature
